[package]
name = "pdbtbx"
version = "0.1.4"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
license = "MIT"
edition = "2018"
description = "A library to open/edit/save (crystallographic) Protein Data Bank (PDB) files."
repository = "https://github.com/nonnominandus/pdbtbx"
readme = "README.md"
keywords = ["pdb", "crystal", "protein", "pdb-parser"]
categories = ["parser-implementations", "science"]

[profile.dev]
opt-level = 3