[package]
name = "rust-pdb"
version = "0.1.0"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
